# Generated by Django 2.2.5 on 2020-03-22 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguridad', '0014_auto_20200322_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, choices=[('INACTIVO', 'Inactivo'), ('ACTIVO', 'Activo')], default='ACTIVO', max_length=45, null=True)),
                ('persona', models.ForeignKey(db_column='persona_alumno', on_delete=django.db.models.deletion.CASCADE, related_name='fk_persona_alumno', to='seguridad.Personas')),
            ],
            options={
                'verbose_name': 'alumno',
                'verbose_name_plural': ('alumnos',),
                'db_table': 'alumno',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_materia', models.CharField(max_length=45)),
                ('estado', models.CharField(blank=True, choices=[('INACTIVO', 'Inactivo'), ('ACTIVO', 'Activo')], default='ACTIVO', max_length=45, null=True)),
            ],
            options={
                'verbose_name': ('materia',),
                'verbose_name_plural': ('materias',),
                'db_table': 'materia',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id_profesor', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, choices=[('INACTIVO', 'Inactivo'), ('ACTIVO', 'Activo')], default='ACTIVO', max_length=45, null=True)),
                ('materia', models.ForeignKey(db_column='id_materia', on_delete=django.db.models.deletion.CASCADE, to='asignacion.Materia')),
                ('persona', models.ForeignKey(db_column='persona_profesor', on_delete=django.db.models.deletion.CASCADE, related_name='fk_persona_profesor', to='seguridad.Personas')),
            ],
            options={
                'verbose_name': 'profesor',
                'verbose_name_plural': ('profesores',),
                'db_table': 'profesor',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('curso', models.CharField(default='ACTIVO', max_length=45)),
                ('descripcion', models.CharField(blank=True, default='sin descripcion', max_length=200, null=True)),
                ('paralelo', models.IntegerField()),
                ('estado', models.CharField(blank=True, choices=[('INACTIVO', 'Inactivo'), ('ACTIVO', 'Activo')], default='ACTIVO', max_length=45, null=True)),
                ('alumnos', models.ManyToManyField(db_table='alumno_curso', to='asignacion.Alumno')),
                ('profesor', models.ForeignKey(db_column='profesor_curso', on_delete=django.db.models.deletion.CASCADE, related_name='fk_curso_profesor', to='asignacion.Profesor')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': ('cursos',),
                'db_table': 'curso',
            },
        ),
    ]
