# Generated by Django 2.2.5 on 2020-03-23 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='alumnos',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='profesor',
        ),
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asignacion.Curso'),
        ),
        migrations.DeleteModel(
            name='Materia',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
