# Generated by Django 2.2.5 on 2020-03-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0002_auto_20200323_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='curso',
            name='paralelo',
            field=models.CharField(max_length=12),
        ),
    ]
