# Generated by Django 2.2.5 on 2020-03-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0004_asignar_examen'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignar_examen',
            name='estado',
            field=models.CharField(blank=True, choices=[('INACTIVO', 'Inactivo'), ('ACTIVO', 'Activo')], default='ACTIVO', max_length=45, null=True),
        ),
    ]
