# Generated by Django 2.2.5 on 2020-03-21 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_padre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.Menu'),
        ),
        migrations.AddField(
            model_name='menu',
            name='tipo_menu',
            field=models.CharField(choices=[('PADRE', 'Inactivo'), ('HIJO', 'Activo')], default=0, max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('PROFESOR', 'Profesor'), ('ADMINISTRADOR', 'Administrador'), ('ALUMNO', 'Alumno')], max_length=50),
        ),
    ]
