# Generated by Django 2.2.5 on 2020-03-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0003_auto_20200321_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='tipo_menu',
            field=models.CharField(choices=[('PADRE', 'padre'), ('HIJO', 'hijo')], max_length=45),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(default='#', max_length=60),
        ),
    ]
