# Generated by Django 2.2.5 on 2020-03-21 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0004_auto_20200321_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_padre',
            field=models.ForeignKey(blank=True, db_column='menu_padre', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.Menu'),
        ),
    ]
