# Generated by Django 2.2.5 on 2020-03-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0005_auto_20200321_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='foto',
            field=models.ImageField(default='default/default_avatar.png', upload_to='usuarios_avatar'),
        ),
    ]
