# Generated by Django 2.2.5 on 2020-03-21 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0006_auto_20200321_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permisos',
            name='usuario',
        ),
        migrations.AddField(
            model_name='permisos',
            name='rol',
            field=models.ForeignKey(db_column='id_rol', default=2, on_delete=django.db.models.deletion.CASCADE, related_name='fk_rol', to='seguridad.Roles'),
            preserve_default=False,
        ),
    ]
