# Generated by Django 2.2.5 on 2020-03-21 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0007_auto_20200321_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol_usuario',
            field=models.ForeignKey(db_column='rol_usuario', on_delete=django.db.models.deletion.CASCADE, to='seguridad.Roles'),
        ),
    ]
