# Generated by Django 2.2.5 on 2020-03-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0008_auto_20200321_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisos',
            name='estado',
            field=models.CharField(choices=[('INACTIVO', 'Inactivo'), ('ACTIVO', 'Activo')], default='ACTIVO', max_length=50),
            preserve_default=False,
        ),
    ]
