# Generated by Django 2.2.5 on 2020-03-22 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0009_permisos_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisos',
            name='rol',
            field=models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, related_name='fk_rol', to='seguridad.Roles', unique=True),
        ),
    ]
