# Generated by Django 2.2.5 on 2020-03-22 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0010_auto_20200322_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisos',
            name='estado',
            field=models.CharField(blank=True, choices=[('INACTIVO', 'Inactivo'), ('ACTIVO', 'Activo')], default='ACTIVO', max_length=50, null=True),
        ),
    ]
