# Generated by Django 2.2.5 on 2020-03-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0012_auto_20200322_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='rol_nombre',
            field=models.CharField(choices=[('PROFESOR', 'Profesor'), ('ADMINISTRADOR', 'Administrador'), ('ALUMNO', 'Alumno'), ('EMPLEADO_ADMINITRATIVO', 'Empleado administrativo')], max_length=45),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('INACTIVO', 'Inactivo'), ('ACTIVO', 'Activo')], default='ACTIVO', max_length=50, null=True),
        ),
    ]
