# Generated by Django 2.2.5 on 2020-03-22 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0013_auto_20200322_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='rol_nombre',
            field=models.CharField(choices=[('PROFESOR', 'Profesor'), ('ADMINISTRADOR', 'Administrador'), ('ALUMNO', 'Alumno'), ('EMPLEADO ADMINITRATIVO', 'Empleado administrativo')], max_length=45),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_persona',
            field=models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, to='seguridad.Personas', unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=45),
        ),
    ]
