# Generated by Django 2.2.5 on 2020-03-25 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0014_auto_20200322_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='orden',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
