# Generated by Django 2.2.5 on 2020-03-06 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id_examen', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(db_column='usuario', on_delete=django.db.models.deletion.CASCADE, related_name='autor_del_examen', to='seguridad.Usuario')),
            ],
            options={
                'verbose_name': ('Examen',),
                'verbose_name_plural': ('Examenes',),
                'db_table': 'examen'
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.TextField(max_length=200)),
                ('opcion1', models.CharField(max_length=100)),
                ('opcion2', models.CharField(max_length=100)),
                ('respuesta', models.CharField(max_length=100)),
                ('examen', models.ForeignKey(db_column='id_examen', on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_del_examen', to='evaluacion.Examen')),
            ],
            options={
                'verbose_name': ('Pregunta',),
                'verbose_name_plural': ('Preguntas',),
                'db_table': 'preguntas'
            },
        ),
    ]
