# Generated by Django 2.2.5 on 2020-03-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opciones',
            fields=[
                ('id_opcion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('estato', models.CharField(blank=True, choices=[('INACTIVO', 'Inactivo'), ('ACTIVO', 'Activo')], default='ACTIVO', max_length=45, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='opcion1',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='opcion2',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='respuesta',
        ),
        migrations.AlterField(
            model_name='examen',
            name='estado',
            field=models.CharField(blank=True, choices=[('INACTIVO', 'Inactivo'), ('ACTIVO', 'Activo')], default='ACTIVO', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='opciones',
            field=models.ManyToManyField(db_table='pregunta_opciones', to='evaluacion.Opciones'),
        ),
    ]
