# Generated by Django 2.2.5 on 2020-03-22 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0002_auto_20200322_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opciones',
            options={'verbose_name': ('Opcion',), 'verbose_name_plural': ('Opciones',)},
        ),
        migrations.AlterModelTable(
            name='opciones',
            table='opciones',
        ),
    ]
