# Generated by Django 2.2.5 on 2020-03-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0005_auto_20200324_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexos',
            name='nombre',
            field=models.CharField(default=1, max_length=45, unique=True),
            preserve_default=False,
        ),
    ]
