# Generated by Django 2.2.5 on 2020-03-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0008_auto_20200324_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='anexo',
            field=models.TextField(blank=True, default='No agregar anexo', null=True),
        ),
        migrations.DeleteModel(
            name='Anexos',
        ),
    ]
