# Generated by Django 2.2.5 on 2020-03-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0009_auto_20200324_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='estado',
            field=models.CharField(blank=True, choices=[('INACTIVO', 'Inactivo'), ('ACTIVO', 'Activo')], default='ACTIVO', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='estado',
            field=models.CharField(blank=True, choices=[('INACTIVO', 'Inactivo'), ('ACTIVO', 'Activo')], default='ACTIVO', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='respuesta',
            field=models.CharField(choices=[('CORRECTA', 'Correcta'), ('INCORRECTA', 'Incorrecta')], max_length=45),
        ),
    ]
